[package]
name = "tradeServer"
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = "0.8"
encoding_rs = "0.8"
actix-web = "4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
actix-rt = "2.10.0"
once_cell = "1.21.3"

[profile.release]
opt-level = 3
lto = true