name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 只有以 v 开头的 tag 会触发，比如 v1.0.0


jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装 Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: i686-pc-windows-msvc
          override: true

      - name: 编译项目
        run: |
          rustup target add i686-pc-windows-msvc
          cargo build --bin tradeServer --target i686-pc-windows-msvc --release

      - name: 上传编译产物
        uses: actions/upload-artifact@v4
        with:
          name: tradeServer
          path: target/i686-pc-windows-msvc/release/tradeServer.exe

  release:
    needs: build
    runs-on: windows-latest
    steps:
      - name: 下载编译产物
        uses: actions/download-artifact@v4
        with:
          name: tradeServer

      - name: 发布 Release
        uses: softprops/action-gh-release@v1
        with:
          files: tradeServer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}